### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by lilylofts** [BenElijah25/Bust-Out-360#1]
Hi @SufyanMussood could you please send across the logos and other assets you have for Bust Out. 
Thanks Lily :)

**Comment by SufyanMussood** [comment]
Hi Lily, 

Apologies but I don't have access to any of the Bust Out assets. I've not had to work on any projects so it's best to liaise with Adrees Hussain.

**Comment by lilylofts** [comment]
Ok great thank you!
