### ISSUE TITLE
Thumbnail Brief: Bust Out Essex

### ISSUE THREAD

**Issue by BenElijah25** [BenElijah25/Bust-Out-360#10]
Hi @SufyanMussood ,

Can you please create updated thumbnails for the 3 rooms?
The current thumbnails have been updated and they do look nice, but I'm revamping the site and am trying to have a more of a movie-style thumbnail incorporated.

Here are the 3 thumbnails required:
- Head Chef
- Samurai
- Rockstar

These are the current thumbnails:

![Samurai - Essex-min](https://user-images.githubusercontent.com/94052689/197528344-9c55a8f9-87e0-4cc7-89f3-03eaf2d25463.png)

![Logo-min](https://user-images.githubusercontent.com/94052689/197528036-b9e7045e-b383-4272-850d-f0be411d0da8.png)
![Rockstar - Essex-min](https://user-images.githubusercontent.com/94052689/197528048-333bfbad-0511-4fae-ac0b-ed2cc010bd86.png)

Here's more of the direction I'd like to go in. They almost look like movie posters and the only requirements I'd like to see is a small Bust Out 360 logo and the name of the room. 

Can I see something by COP on wednesday?

Thanks,

**Comment by BenElijah25** [comment]
Here's the direction I was talking about:

![image](https://user-images.githubusercontent.com/94052689/197528413-a2a560c0-4e39-4bcd-860f-1f255e9e8a6f.png)

**Comment by BenElijah25** [comment]
Can we do a 9x16 and a 1x1? 

Let's approve one size in styling before replicating onto a different one.

Cheers @SufyanMussood

**Comment by SufyanMussood** [comment]
Samurai

![Dark grey simple samurai warrior action movies promotion poster (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/197836738-e9917dcc-bc13-46e0-9ccc-48dcb4b2b196.png)

**Comment by BenElijah25** [comment]
Love this. Bang on and looks so enticing/exciting. 

Can you pop the Bust Out 360 logo just above the word Samurai and for the others you're working on too please. 

Thanks!

**Comment by SufyanMussood** [comment]
Headchef - I was struggling to create imagery for this without resorting to clipart. I personally think this is far more enticing to look at than the current image because how often is it you'd be required to do a cooking related escape room. I'd be more enticed to look into this more. 

![Black Chef Hiring Advertising Poster (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/198002874-ae32b63a-cc0a-46e8-adda-475798ec44d7.png)

**Comment by SufyanMussood** [comment]
Rockstar - the logo for this escape room is beyond bad man. It's something straight out of a rockband game nonetheless I've used it and provided a few alternatives. The green really doesn't strike Rock N Roll to me nor is green a good colour to highlight poison which is the theme. 

![Black Red Urban Grunge Rock n Roll Concert Program (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/198003301-6591cf38-87c3-4f8f-9aa9-cdb1ec516c85.png)

**Comment by SufyanMussood** [comment]
My preference is this. 

![Black Red Urban Grunge Rock n Roll Concert Program (Instagram Post (Square)) (2)](https://user-images.githubusercontent.com/94172350/198003348-0c24644c-4341-4906-be1c-dec5a9c6d2bb.png)

**Comment by BenElijah25** [comment]
@SufyanMussood - Probably should have mentioned we don't have to use the same theme/logo for the rooms eeeeek. 

I think all 3 need to look cohesive with each other and have that movie style poster that Samurai has. 

Head Chef - I think we could go down the route of kitchen cooking/fire/escaping sort of thing?

Rockstar - Again, probably my bad as hadn't mentioned before but can we use imagery like in Samurai so the three thumbnails look cohesive with eachother?

Thanks,

**Comment by SufyanMussood** [comment]
Rockstar - I've merged two images to make one here. One of the images has a skull attached. A symbol used commonly with Rockstar but also happens to be the default symbol for poison. 

![2](https://user-images.githubusercontent.com/94172350/198009143-64e225e8-3598-43d2-88a4-13b33090666c.png)
![Rockstar](https://user-images.githubusercontent.com/94172350/198009313-04de7755-0478-4feb-b6da-edaaed2321aa.png)

**Comment by BenElijah25** [comment]
Let's use v2 - Looks great

**Comment by BenElijah25** [comment]
Sorry if you're already working on it, but can we rejig the look of HeadChef?

**Comment by SufyanMussood** [comment]
Lowered the logo and increased size 

![Dark grey simple samurai warrior action movies promotion poster (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/198053890-6b664b3c-29e9-4785-be1c-f6abe2f407d7.png)

**Comment by BenElijah25** [comment]
Can we put the logo just about the room name please?

**Comment by BenElijah25** [comment]
Also, do you know what the chinese letters are? Haha

**Comment by SufyanMussood** [comment]
it says Samurai, I hope. lol

**Comment by SufyanMussood** [comment]
I mean this is what I ended up with. Do we like either of these?

![Black White Modern Cooking Secret Youtube Thumbnail (Instagram Post (Square)) (1)](https://user-images.githubusercontent.com/94172350/198078418-60b6ebae-f8c6-4e67-aa23-600829841982.png)

![Black Elegant Food Magazine Cover (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/198078415-11e785f8-ba84-4a33-8f96-d2823e4965c8.png)

**Comment by SufyanMussood** [comment]
Attached @lilylofts 
![Black Elegant Food Magazine Cover (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/200306193-90e6d1b1-60b8-42cc-bd10-c999b195fad9.png)
