### ISSUE TITLE
BustOut Homepage Banner

### ISSUE THREAD

**Issue by SufyanMussood** [BenElijah25/Bust-Out-360#11]
- leave the top black for cta and text

**Comment by BenElijah25** [comment]
Hey @SufyanMussood ,

I'm sure you're working on it but could I squeeze this for today?

Thanks,

**Comment by SufyanMussood** [comment]
Hey before I start, can you test this for me please. I'm trying to pixel count otherwise I don't actually understand how to make the asset

![_Escape Room The Mystery Novel Book Cover (2598 × 872px) (2543 × 734px)](https://user-images.githubusercontent.com/94172350/198019045-7f0d9d8d-91f9-4b15-b684-873521c9037d.png)

**Comment by SufyanMussood** [comment]
can you show me it previews on our site when you go full screen with the browser

**Comment by BenElijah25** [comment]
https://www.bustout360essex.co.uk/
