### ISSUE TITLE
New Room Reel

### ISSUE THREAD

**Issue by lilylofts** [BenElijah25/Bust-Out-360#12]
Hi Suf, 

Can you please create a reel of the new room, it doesn't have to be anything technique just simply doing little scans of the room, you an even then send them to me and i'll add the text and sound. 

It shouldn't take longer than 10-15 mins to do and create.

**Comment by SufyanMussood** [comment]
Spoke to Adrees and he said the room isn't in the right state to record today. He will recording the reels himself on Monday.

**Comment by SufyanMussood** [comment]
@AdreesHussain - assigning this to you.
