### ISSUE TITLE
Slough Thumbnail Redesign

### ISSUE THREAD

**Issue by SufyanMussood** [BenElijah25/Bust-Out-360#13]

**Comment by SufyanMussood** [comment]
![Volcano Modern Minimal Music Album Cover Art (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/200332966-0daf1d1b-dca7-4f0a-a9f6-e54b1aaf92f2.png)
![Copy of Black and Red Simple Horror Book Cover (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/200332974-f84705af-29e3-4e2f-96d9-8b87fa62ade4.png)
![Hijacked](https://user-images.githubusercontent.com/94172350/200332977-1d12dc82-408d-4c18-9a8f-b1da6b38ef2c.png)
![Taken](https://user-images.githubusercontent.com/94172350/200332978-3e3ee20b-229f-42c6-911f-63682658d81a.png)

**Comment by BenElijah25** [comment]
Hey, just a few points:

- Could you please add a question mark on the question taglines?
- They look all look good, however I think Hijacked and Enhanced don't look as enticing as the others, also comparing to the Essex thumbnails, I think we should hit the same "movie feel" with all the thumbnails.
- Taken and Cursed are good to go (once the "?" is added)

Thanks !

**Comment by SufyanMussood** [comment]
Hijacked and Enhanced look the best in my opinion lol. Hijacked is a straight rip of the movie Speed with its poster. Do you want those entirely redone?

**Comment by SufyanMussood** [comment]
I think Taken doesn't require a ? mark. I think its just a statement as oppose to a question.

**Comment by SufyanMussood** [comment]
Cursed redone. 

![Volcano Modern Minimal Music Album Cover Art (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/200552208-b946d783-7f43-4575-80e1-081060ceca2c.png)

**Comment by BenElijah25** [comment]
Sorry meant Hijacked with the "?" 

And yes please, I think it gives off more a stock image vibe than movie style

**Comment by lilylofts** [comment]
Hey Suf, can you please finalise these so I can start putting them up :)

**Comment by SufyanMussood** [comment]
Hey @lilylofts - can you get Ben to provide some more feedback regarding the remaining two thumbnails. I need some ideas, what kind of imagery are we looking for. I thought the two I created do a good job of highlighting the potential of that room.

**Comment by BenElijah25** [comment]
Enhanced - You and your team have secretly dedicated your lives to developing a way to grant super powers to the masses & create real life super heroes.

The government have found out and are threatening to close your lab permanently. No lab assistants & no test subjects are available, if you want to make this possible, you’re going to have to develop the drug and test it on yourself…

This is your last chance to change the world.

Can we use something a little more exciting? The image currently does have a sharp look but I think the description sounds alot more exciting than the image. The goal to be making people stop scrolling. We could go down the superhero route, or go down the "lab" route. 

Hijacked - The imagery seems fairly old. The actual train seems dated, if we could use updated train or something that nods to more of a modern look?

Let me know if that works or give me a call

Cheers!

**Comment by lilylofts** [comment]
Hey Suf, do you have an update on these?

**Comment by lilylofts** [comment]
Need them asap please, if not i'll have to use what you've done so far as it's for an email that's going out today

**Comment by SufyanMussood** [comment]
I haven't gotten to this yet. I won't be able to produce something worthwhile until I have assets I can work with.

**Comment by SufyanMussood** [comment]
Here's what I could piece for Enhanced. One of them is very comic booky but I'm just testing what I can at this point. 
![Yellow Heroic Simple And Minimalist Father Day Poster (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/201978410-a28f95c4-bf43-4627-8cc8-9a880f0a9c5a.png)

![Blue and White Funny Motivational Coffee Superhero Meme (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/201978391-9392f2c2-23ec-4296-abd9-9117f8e6b94c.png)
![Yellow and Grey Modern Amazing Superhero Book Cover (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/201978444-ca462c35-9ae6-4471-9bf7-93527041651b.png)
![Enhanced Thumbnail](https://user-images.githubusercontent.com/94172350/201978455-d7b039aa-f14c-46c6-b514-58e7e6e652c2.png)

**Comment by SufyanMussood** [comment]
@BenElijah25 what do you think of the last one?

**Comment by SufyanMussood** [comment]
I was thinking of maybe adding a drug bottle next to him on the wall

**Comment by SufyanMussood** [comment]
![Untitled-1](https://user-images.githubusercontent.com/94172350/201984576-701dbf93-3c93-41b1-850a-83c4045ebca1.png)

**Comment by SufyanMussood** [comment]
How's this image for hijacked

**Comment by SufyanMussood** [comment]
This is what I've got for hijacked 

![Long Trip Modern Minimal Music Album Cover Art (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/202014411-cd44254a-1539-4dc4-affc-88164490efce.png)

**Comment by SufyanMussood** [comment]
Compressed images attached - marking as complete 

![Enhanced Thumbnail copy](https://user-images.githubusercontent.com/94172350/202176214-a05e9f87-ed7d-48c8-8bbb-85dcce18b58c.jpg)


![Long Trip Modern Minimal Music Album Cover Art (Instagram Post (Square))](https://user-images.githubusercontent.com/94172350/202176330-c08a7545-a086-41f9-945a-8b2b386f14c5.png)
