### ISSUE TITLE
Trade Tracker Banners - Deadline 2-12-22

### ISSUE THREAD

**Issue by lilylofts** [BenElijah25/Bust-Out-360#16]
Hey Suf, 

I need 6 banners for our Trade Tracker site. All I need you to do is resize the thumbnail images to the sizes below. 
They all must have the BO logo on them too. 

Any questions please give me a call. It should be a pretty easy straight forward job which I would do but I don't have the original artwork. 

- 120 x 600 pixels
- 125 x 125 pixels
- 400 x 400 pixels
- 970 x 250 pixels

Thanks 
Lily

**Comment by SufyanMussood** [comment]
im just seeing this

**Comment by lilylofts** [comment]
No worries, can you please work on it before 2pm, as mentioned it shouldn't take to long to do

**Comment by SufyanMussood** [comment]
Here's Cursed:

![Volcano Modern Minimal Music Album Cover Art (120 × 600px)](https://user-images.githubusercontent.com/94172350/205282124-85bf8984-28fb-45d4-8b74-8115e0a448ae.png)
![Volcano Modern Minimal Music Album Cover Art (125 × 125px) (400 × 400px)](https://user-images.githubusercontent.com/94172350/205282127-f3f91660-6b14-479d-820c-91f0df3e3015.png)
![Volcano Modern Minimal Music Album Cover Art (125 × 125px)](https://user-images.githubusercontent.com/94172350/205282131-5ec18f62-f554-4860-b769-55347d541326.png)
![Volcano Modern Minimal Music Album Cover Art (970 × 250px)](https://user-images.githubusercontent.com/94172350/205282132-f6a90027-faf9-4d1f-a42b-bfb35763fdc4.png)

**Comment by lilylofts** [comment]
I also need the writing on it, with the question please

**Comment by lilylofts** [comment]
![Cursed](https://user-images.githubusercontent.com/99664588/205282379-ccf613dc-8332-413a-86b4-3925f6b348b0.png)
![Hijacked 2](https://user-images.githubusercontent.com/99664588/205282387-267b02d5-cdc4-45d6-a5d1-4ad8e1b
![Taken](https://user-images.githubusercontent.com/99664588/205282396-6bf05d10-cf17-44cf-9528-0663725bff26.png)
41a54.png)

**Comment by lilylofts** [comment]
Could you please also make them in the following sizes 

- 160 x 600 pixels
- 180 x 150 pixels
- 336 x 280 pixels
- 500 x 500 pixels

**Comment by SufyanMussood** [comment]
wait, can you finalise this brief please. Am i doing 8 sizes or 4?

**Comment by lilylofts** [comment]
Ok new brief, 

Can you please create 8 sizes (dims below) for the thumbnails for each room, please include the question wording as shared in the images above. If you need to add this to the side of the image then please do so. 

160 x 600 pixels
180 x 150 pixels
336 x 280 pixels
500 x 500 pixels
120 x 600 pixels
125 x 125 pixels
400 x 400 pixels
970 x 250 pixels

Thanks 
Lily

**Comment by SufyanMussood** [comment]
![Untitled (160 × 600px) (180 × 150px)](https://user-images.githubusercontent.com/94172350/205288483-4d81c673-fe4c-43ce-a139-6146bc5f9665.png)
![Untitled (160 × 600px)](https://user-images.githubusercontent.com/94172350/205288486-66742ba3-9088-43a9-bd66-f93191b0e2a6.png)
![Volcano Modern Minimal Music Album Cover Art (160 × 600px) (180 × 150px) (336 × 280px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px) (400 × 400px) (970 × 250px)](https://user-images.githubusercontent.com/94172350/205288487-a2ee8c0c-3395-4b6b-b38c-ee2eedb07f01.png)
![Volcano Modern Minimal Music Album Cover Art (160 × 600px) (180 × 150px) (336 × 280px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px) (400 × 400px)](https://user-images.githubusercontent.com/94172350/205288488-2bd1feb5-6333-4daa-b411-ddfc023a1467.png)
![Volcano Modern Minimal Music Album Cover Art (160 × 600px) (180 × 150px) (336 × 280px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px)](https://user-images.githubusercontent.com/94172350/205288489-98448b3e-7b7c-4ca1-8cbc-48837479b157.png)
![Volcano Modern Minimal Music Album Cover Art (160 × 600px) (180 × 150px) (336 × 280px) (336 × 280px) (500 × 500px) (120 × 600px)](https://user-images.githubusercontent.com/94172350/205288490-eef7fa13-6f69-4b8d-ab36-d0089fd39826.png)
![Volcano Modern Minimal Music Album Cover Art (160 × 600px) (180 × 150px) (336 × 280px) (336 × 280px) (500 × 500px)](https://user-images.githubusercontent.com/94172350/205288494-42c48ccc-b959-46a6-b906-fed12befe05b.png)
![Volcano Modern Minimal Music Album Cover Art (160 × 600px) (180 × 150px) (336 × 280px) (336 × 280px)](https://user-images.githubusercontent.com/94172350/205288495-a22c8f79-1e7c-4ce4-a7ae-58169ee1ee3d.png)
![Volcano Modern Minimal Music Album Cover Art (160 × 600px) (180 × 150px)](https://user-images.githubusercontent.com/94172350/205288497-fa2c69fe-a916-4adb-8dc5-3592ad7ab9b8.png)
![Volcano Modern Minimal Music Album Cover Art (160 × 600px)](https://user-images.githubusercontent.com/94172350/205288498-73017be3-4f07-4e71-a89c-489b21e96d80.png)
![Black and Red Simple Horror Book Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px) (400 × 400px) (970 × 250px)](https://user-images.githubusercontent.com/94172350/205288500-118a5f0c-153e-405f-bbd6-182045f4367d.png)
![Black and Red Simple Horror Book Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px) (400 × 400px)](https://user-images.githubusercontent.com/94172350/205288501-be7c29d2-f9ea-4ab0-828b-ff91e688f642.png)
![Black and Red Simple Horror Book Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px)](https://user-images.githubusercontent.com/94172350/205288505-2cf1d551-9ba3-43a4-b40a-d049e19886eb.png)
![Black and Red Simple Horror Book Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px)](https://user-images.githubusercontent.com/94172350/205288508-bb11d91d-3eee-4cb9-88b0-8bac0937d03e.png)
![Black and Red Simple Horror Book Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px)](https://user-images.githubusercontent.com/94172350/205288509-ad03c4c4-460e-4888-bc06-796d3f0ce56d.png)
![Black and Red Simple Horror Book Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px)](https://user-images.githubusercontent.com/94172350/205288511-2674e9d0-a0c5-40fa-a0e4-6351be03f9b3.png)
![Black and Red Simple Horror Book Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px)](https://user-images.githubusercontent.com/94172350/205288512-8032bc43-568e-49c0-93a9-2d4e82cf90b3.png)
![Black and Red Simple Horror Book Cover (Instagram Post (Square)) (160 × 600px)](https://user-images.githubusercontent.com/94172350/205288513-8ba2a762-df9f-453f-9a89-31758922149e.png)
![Long Trip Modern Minimal Music Album Cover Art (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px) (400 × 400px) (970 × 250px)](https://user-images.githubusercontent.com/94172350/205288514-b34cafe4-b0d3-4937-a502-28cbb070fdba.png)
![Long Trip Modern Minimal Music Album Cover Art (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px) (400 × 400px)](https://user-images.githubusercontent.com/94172350/205288515-53ee0e53-60b0-4ebe-9160-84fb745cbb49.png)
![Long Trip Modern Minimal Music Album Cover Art (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px)](https://user-images.githubusercontent.com/94172350/205288517-48be110c-6821-4c12-9036-1ca40c686915.png)
![Long Trip Modern Minimal Music Album Cover Art (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px)](https://user-images.githubusercontent.com/94172350/205288519-e60b8ad5-449f-4652-9bfe-575e3e57786c.png)
![Long Trip Modern Minimal Music Album Cover Art (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px)](https://user-images.githubusercontent.com/94172350/205288520-7760a329-dd66-48a9-9598-5f962b585eda.png)
![Long Trip Modern Minimal Music Album Cover Art (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px)](https://user-images.githubusercontent.com/94172350/205288524-ced1bb93-c3c8-4065-ba7b-6e5ef169e3b4.png)
![Long Trip Modern Minimal Music Album Cover Art (Instagram Post (Square)) (160 × 600px) (180 × 150px)](https://user-images.githubusercontent.com/94172350/205288525-43e4b50b-61fc-4f8c-8e15-92fffcd5c03e.png)
![Long Trip Modern Minimal Music Album Cover Art (Instagram Post (Square)) (160 × 600px)](https://user-images.githubusercontent.com/94172350/205288527-eca8f5e0-5072-4570-b148-812972951226.png)
![Untitled (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px) (400 × 400px) (970 × 250px)](https://user-images.githubusercontent.com/94172350/205288529-327a8d54-6af7-4e2d-bb53-b0796ca3392f.png)
![Untitled (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px) (400 × 400px)](https://user-images.githubusercontent.com/94172350/205288532-990555df-a13e-4472-909e-029c44e7ec2e.png)
![Untitled (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px)](https://user-images.githubusercontent.com/94172350/205288534-2782e650-7244-4851-a1ab-9a449df3d4f7.png)
![Untitled (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px)](https://user-images.githubusercontent.com/94172350/205288535-25c16033-7d96-405f-9d7e-ec260eaa00ea.png)
![Untitled (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px)](https://user-images.githubusercontent.com/94172350/205288537-ca63f41f-4a3c-4560-b563-00c8a641746c.png)
![Untitled (160 × 600px) (180 × 150px) (336 × 280px)](https://user-images.githubusercontent.com/94172350/205288538-0bc9c389-d232-4c7b-b7b9-784d40ed381b.png)

**Comment by lilylofts** [comment]
Thanks Suf, can you please also do Essex. 

Also did you have them on a folder at all?

**Comment by SufyanMussood** [comment]
![Dark grey simple samurai warrior action movies promotion poster (Instagram Post (Square)) (180 × 150px) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px)](https://user-images.githubusercontent.com/94172350/205307796-874a1a67-d7f2-4968-809a-06be20e3e9ff.png)
![Dark grey simple samurai warrior action movies promotion poster (Instagram Post (Square)) (180 × 150px) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px)](https://user-images.githubusercontent.com/94172350/205307801-a6a7d4f2-bd4b-4dcb-840b-31b47f4a2e33.png)
![Dark grey simple samurai warrior action movies promotion poster (Instagram Post (Square)) (180 × 150px) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px)](https://user-images.githubusercontent.com/94172350/205307805-f7caa62a-4e86-409d-972e-7c7e408e174f.png)
![Dark grey simple samurai warrior action movies promotion poster (Instagram Post (Square)) (180 × 150px) (160 × 600px) (180 × 150px) (336 × 280px)](https://user-images.githubusercontent.com/94172350/205307807-927e8b21-5c7c-4be7-94cc-4a54dd88b5c3.png)
![Dark grey simple samurai warrior action movies promotion poster (Instagram Post (Square)) (180 × 150px) (160 × 600px) (180 × 150px)](https://user-images.githubusercontent.com/94172350/205307809-3460812e-e992-4116-ab30-edaf305d289c.png)
![Dark grey simple samurai warrior action movies promotion poster (Instagram Post (Square)) (180 × 150px) (160 × 600px)](https://user-images.githubusercontent.com/94172350/205307811-81a10e99-dda4-4560-bcfb-43e497fd2e87.png)
![Black Elegant Food Magazine Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (125 × 125px) (400 × 400px) (970 × 250px) (120 × 600px)](https://user-images.githubusercontent.com/94172350/205307813-f43f1f08-6ba0-4541-adff-94d500e6c997.png)
![Black Elegant Food Magazine Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (125 × 125px) (400 × 400px) (970 × 250px)](https://user-images.githubusercontent.com/94172350/205307815-4fad972d-c746-451a-aa2b-c937ced92f0c.png)
![Black Elegant Food Magazine Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (125 × 125px) (400 × 400px)](https://user-images.githubusercontent.com/94172350/205307816-522e1856-812e-4ecc-828a-6fb23b3a1e73.png)
![Black Elegant Food Magazine Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (125 × 125px)](https://user-images.githubusercontent.com/94172350/205307818-d4826256-0307-4eb3-a61a-102fdce018f5.png)
![Black Elegant Food Magazine Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px)](https://user-images.githubusercontent.com/94172350/205307820-b425b5b2-bfa9-4834-8a76-17006f010c32.png)
![Black Elegant Food Magazine Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px)](https://user-images.githubusercontent.com/94172350/205307821-f221589a-2ea0-4401-99aa-296d07e01bcf.png)
![Black Elegant Food Magazine Cover (Instagram Post (Square)) (160 × 600px) (180 × 150px)](https://user-images.githubusercontent.com/94172350/205307824-57358ed9-a963-4ce1-a52e-0dd7884232cf.png)
![Black Elegant Food Magazine Cover (Instagram Post (Square)) (160 × 600px)](https://user-images.githubusercontent.com/94172350/205307825-e4c9172c-475b-4b04-aee0-b9d46a540423.png)
![Black Red Urban Grunge Rock n Roll Concert Program (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (500 × 500px) (125 × 125px) (1)](https://user-images.githubusercontent.com/94172350/205307826-368685a5-edc9-46ff-bc0b-7d50b7ffbf90.png)
![Black Red Urban Grunge Rock n Roll Concert Program (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (500 × 500px) (125 × 125px) (400 × 400px) (400 × 400px) (970 × 250px) (120 × 600p](https://user-images.githubusercontent.com/94172350/205307827-5055a1be-4186-471e-b574-dcfa162aea55.png)
![Black Red Urban Grunge Rock n Roll Concert Program (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (500 × 500px) (125 × 125px) (400 × 400px) (400 × 400px) (970 × 250px)](https://user-images.githubusercontent.com/94172350/205307828-e2bd2ad1-a1aa-4e39-85ae-99754f7c60bb.png)
![Black Red Urban Grunge Rock n Roll Concert Program (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (500 × 500px) (125 × 125px) (400 × 400px) (400 × 400px)](https://user-images.githubusercontent.com/94172350/205307830-14ccf6cf-e719-40b8-bcc7-2d63b9a84b09.png)
![Black Red Urban Grunge Rock n Roll Concert Program (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (500 × 500px) (125 × 125px)](https://user-images.githubusercontent.com/94172350/205307831-78d3ad2b-107d-462a-847b-72833cd5301c.png)
![Black Red Urban Grunge Rock n Roll Concert Program (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (500 × 500px)](https://user-images.githubusercontent.com/94172350/205307834-1b3fa37d-abb6-4202-856c-96491c342682.png)
![Black Red Urban Grunge Rock n Roll Concert Program (Instagram Post (Square)) (160 × 600px) (180 × 150px) (336 × 280px)](https://user-images.githubusercontent.com/94172350/205307837-cd492678-645d-4987-b2f7-5117667b5039.png)
![Black Red Urban Grunge Rock n Roll Concert Program (Instagram Post (Square)) (160 × 600px) (180 × 150px)](https://user-images.githubusercontent.com/94172350/205307839-7a1b9562-ee15-428f-a9ac-b57cbcf70083.png)
![Black Red Urban Grunge Rock n Roll Concert Program (Instagram Post (Square)) (160 × 600px)](https://user-images.githubusercontent.com/94172350/205307841-0b18dc57-b098-4eb1-8272-760c7b50202b.png)
![Dark grey simple samurai warrior action movies promotion poster (Instagram Post (Square)) (180 × 150px) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px) (400 × 400px) (970 × 250px](https://user-images.githubusercontent.com/94172350/205307843-052b9e55-c878-491b-ab81-e4ead846c8d8.png)
![Dark grey simple samurai warrior action movies promotion poster (Instagram Post (Square)) (180 × 150px) (160 × 600px) (180 × 150px) (336 × 280px) (500 × 500px) (120 × 600px) (125 × 125px) (400 × 400px)](https://user-images.githubusercontent.com/94172350/205307844-f660e940-cf9d-486d-b513-68166d37da4e.png)

**Comment by lilylofts** [comment]
Thank you
