### ISSUE TITLE
TikTok Asset Creation

### ISSUE THREAD

**Issue by BenElijah25** [BenElijah25/Bust-Out-360#2]
Hi @lilylofts Adrees,

Could you please work together and assign a specific amount of content to be shared in the Teams drive every X day so we can reach our minimum expectation of content every day.

Thanks!

**Comment by AdreesHussain** [comment]
Hi all,

Following on from the meeting Lily and I had this morning, we've come up with the following minimum weekly video quota. This is of course adjustable as we get more ideas but will be the starting point.

2 x Escape Room Tips
2 x Trends (any popular sounds, videos formats etc that are trending. Can also be added off the cuff)
2 x Brainteasers (anagrams/riddles that will be a 10% discount code on the website)
3 x Funny (escape room related or general)
2 x In the Room (likely to increase, but minimum 2)
1-2 x Behind the Scenes (new room creation, repairs, design insight)
1 x Dear... (different groups of people who enter rooms)
1 x Most Annoying Things (that GMs hear or people do or things we hear 2568026 times a week)

Folders for each of these are created on Teams and I will update them regularly. Lily also has a Bust Out jacket to film any videos off the cuff.

If we ensure that by Thursday midday all content for the following week is available on Teams. If anything is missing, this can be created at the weekend as that is when I am usually spending the most time at Bust Out. I will also update Raisa on what content to record.

Thanks

**Comment by BenElijah25** [comment]
Perfect. 

Thanks @AdreesHussain @lilylofts

**Comment by lilylofts** [comment]
Great, thanks @AdreesHussain Adress. 

Can you please make sure you send me x10 new videos every Thursday so I can schedule them for the next week. I'll send a reminder in the calendar.

**Comment by lilylofts** [comment]
Hi @AdreesHussain 

Can you please send across some more content today so I can create some content for next week. 

Thanks 
Lily

**Comment by BenElijah25** [comment]
@AdreesHussain - Have we sent over more content?

Cheers
