### ISSUE TITLE
Bustout Ad 

### ISSUE THREAD

**Issue by SufyanMussood** [BenElijah25/Bust-Out-360#3]
Scouting | 29-07
Storyboarding | 29-07

**Comment by SufyanMussood** [comment]
Here's my idea for the ad with images attached for reference:

Ad Length: 30secs to 1min
Aim: Introduce the viewer to Bustout & the idea/concept behind the 3 rooms available. 
Composition: The ad will be shot from a first person perspective. 

Title: SLOUGH....14.00PM
**Shot 1:**  

We hear heavy panting/breathing. Fade in from black with a guy running through the bust out hallway. Quickly turns back to hear the door shut and see's the Bustout 360 logo for a moment before running to the end of the hallway and stopping to look ahead. 
![20220729_101437](https://user-images.githubusercontent.com/94172350/184701465-7fb23a63-ff84-428c-ac22-b4b026c55005.jpg)
![20220729_101435](https://user-images.githubusercontent.com/94172350/184701734-c8862712-e2bc-4f59-8544-002a9e5b94a5.jpg)

**Shot 2:** 

The guy runs down the hallway attempting to open 1 of 3 doors only to find it locked and then attempts door 2 which is open leading us into our first escape room, Taken. This intro is the perfect segway into Taken as the individual is running from someone or something so it's alluding to the fact that he's been taken and is trapped. 
![20220729_101428](https://user-images.githubusercontent.com/94172350/184703082-61fded5c-3df3-4f8b-85d6-ac0260c95884.jpg)

**Shot 3:**

In the room, we may have images appearing on the TV, like a newscaster (which one of us can voice) explaining that there's been multiple disappearances in Slough and so on. A very brief overview of the room is essentially explained to the viewer and the tv cuts out to the bustout logo once again. The individual attempts to look for a way out and the secret passageway is revealed. As you move through the black curtains, we'll cut to the next room which is Cursed. 

**Shot 4:** 

So my thinking is the guy will crawl out of the closet and mask that as the transition. In the Cursed room, the lighting, music will be very different to that of Taken. It will give off a more adventure vibe with the guy exploring the room and objects. The secret passageway into the next room with the skulls is revealed and he runs through there. 
![20220729_102257](https://user-images.githubusercontent.com/94172350/184703422-f5f554cd-65b5-4234-967e-f84899294c9b.jpg)

**Shot 5:** 

In the artefact room, we'll have the candles on and the artefact itself somewhat glowing. As the individual attempts to touch the artefact, we see the candles on the skull begin to flicker and the sound of a train draws in. The candles go out entirely dipping us into black. 
![20220729_102215](https://user-images.githubusercontent.com/94172350/184704018-004d1a16-1600-4205-b326-d0e75723fc7c.jpg)
![20220729_102220](https://user-images.githubusercontent.com/94172350/184704026-40efe41e-fc18-4fc0-b484-7bdfd2fd67ac.jpg)

**Shot 6:** 
Fading in from black we are in the final escape room, Hijacked. Here we can hear the train nearing the end of the line and our guy panicking as he tries to solve a puzzle of sorts. The windows will have a video playing giving us the constant illusion of movement. 
![20220729_102403](https://user-images.githubusercontent.com/94172350/184704255-e8eb0dbc-35e6-40d0-bc99-d1343ee3ba7d.jpg)
![20220729_102407](https://user-images.githubusercontent.com/94172350/184704271-a5f293b6-2179-461b-b05c-b5ba582f481e.jpg)

**Shot 7**
Finally the puzzle is solved and the guy runs into the main console room. We see that we need to enter a password into the console. 3 attempts in total. 
First attempt is: ESCAPEROOM
Second is: BustOut
Final Attempt: BustOut 360
The guy hits the brake and we see the train coming to a halt but before we see it fully stop, we fade to white, and the logo is revealed. 
![20220729_103314](https://user-images.githubusercontent.com/94172350/184704935-6a614158-6f87-4ac3-ba94-d08361ebddd9.jpg)
![20220729_103449](https://user-images.githubusercontent.com/94172350/184704945-96eb0e5c-9a6b-4073-a385-f9625c436cab.jpg)
![20220729_103455](https://user-images.githubusercontent.com/94172350/184704953-36c0417f-cb1e-4baa-9c29-c03badd20576.jpg)


_A couple of points from me - this ad will be sound fx heavy and will utilise 3 different pieces of background music for the 3 rooms. Throughout the whole ad, we'll have a clock ticking. At the start it will be very faint but towards the end, it will get louder._ 

@BenElijah25 - let me know your thoughts and we can discuss how to shoot and the setup needed.

**Comment by SufyanMussood** [comment]
@BenElijah25 - Also Ben, I think if we could borrow a GoPro or Gimbal for this shoot, it would help massively. If we need to purchase an item, then we definitely need a gimbal for future content across all businesses anyways.

**Comment by SufyanMussood** [comment]
https://youtu.be/GylIK-7R5Kg

**Comment by SufyanMussood** [comment]
- the start should say Bust Out 360 (bust and out are separate words)

- let's add the following text at these times, just flashing up, maybe with a glitch effect:
0:02 - award-winning escape rooms
0:08 - 4 incredible games
0:13 - fully immersive entertainment
0:17 - Taken logo
0:21 - escape your kidnapper
0:28 - hijacked logo
0:32 - stop a hijacked train
0:42 - cursed logo
0:46 - prevent an apocalypse
0:54 - enhanced logo
0:58 - give yourself super powers

- if we can shave off 10 seconds to get it under 60 seconds that would be great. Maybe speed up the parts inside the room slightly or cut down the length of the shots

- instead of the logos flashing at the end, could it say 'perfect for' 'families, friends, couples, birthdays, team-building, parties' with each of the latter flashing after each other.

- logo + website and socials - ig, fb, Tiktok

**Comment by SufyanMussood** [comment]
16x9 Add Linked Here: https://youtu.be/3K6q_mHjPfk
1x1 Linked Here: https://youtube.com/shorts/oaNdlT4ZO24?feature=share

Also added the source files to Teams. @AdreesHussain or @JulianaEE  can you upload to the Bustout Youtube channel as I do not have access to this.

**Comment by SufyanMussood** [comment]
Teams location is - Marketing - Video content - Bustout Ad#1

**Comment by AdreesHussain** [comment]
Hi, I want to reopen this as I'm still not 100% on the ad. I think the addition of the text helps, but the text needs to be more prominent. If we can use the Filson Pro Black font in CAPS and much bigger, maybe 60% of the screen, then I'll be happy to sign off.

**Comment by SufyanMussood** [comment]
This is uploading to the same location on Teams with changes to font and sizing.

**Comment by SufyanMussood** [comment]
Corrected ad: https://youtu.be/1uSa9c_2oq8
