### ISSUE TITLE
Social assets for Slough - Ongoing assets creation 

### ISSUE THREAD

**Issue by lilylofts** [BenElijah25/Bust-Out-360#4]
Hi Suf, 

We need to create some social assets (images and reels) for Bust Out 360. 

I'm happy for you to have free reign with these as we don't really have brand guidelines a such to go on, here is the assets I've made and scheduled so far. 

You may have to go and get images from the rooms or ask Adrees for some more. 

Any questions please let me know.

**Comment by lilylofts** [comment]
Ethical Enterprises Ltd\Bust Out 360 - General\Social Assets\Slough

**Comment by lilylofts** [comment]
Hi Suf, where are you at with these?

**Comment by SufyanMussood** [comment]
- images of the room
- images of the objects and clues
- speak with adrees about additional imagery
