### ISSUE TITLE
Retargeting Image Ad

### ISSUE THREAD

**Issue by rashedethical** [BenElijah25/Bust-Out-360#6]
Hi @SufyanMussood,

We need a retargeting image ad creating please.  I've added more information below. 

**Please let me know when to set the deadline after considering your current workload.**

Here is the old retargeting ad. I think it's a good starting point:

https://user-images.githubusercontent.com/94128405/183624440-ac5906f0-8ed6-4d2d-9164-ccf5e8d8c291.mp4

I'd like to leave it to you to use your creativity to come up with the ad, but here are a few tweaks that we discussed dover the phone earlier today.

- Discount code (ESCAPE10) needs to be mentioned somewhere
- Use the hero banner image on the website somewhere in the ad to create a consistent journey between the ad and the website
- I liked your idea of having an image of someone in the room and then flashing the logo a few times. 
- There needs to be a call to action at the end of the ad - something like ' book an escape room now' or 'bookings available from one hour'. 
- I like the idea of mentioning 'Go' at the end of the ad. It makes it sound exciting and fun. This is the feeling that we want people to feel when it comes to booking an escape room.  

The image sizes that we need are:

1.91:1, minimum 600 x 314
1:1, minimum 300 x 300

We're going to do this on the Slough website and the Essex website. So we need a variant for each branch please. 

Regards

Rashed

@BenElijah25

**Comment by rashedethical** [comment]
Hi Sufyan,

So a little more information on what I think we should have in the image ad 

The ad would be very similar to the ad in the original brief. 

The first part of the ad would have the below image and message. Maybe the image could be slowly zooming in, or moving in some way??

![image](https://user-images.githubusercontent.com/94128405/184862636-b74b8215-3a5a-4d09-8467-254a33d77a2b.png)


The second part of the ad would something like the below:

![image](https://user-images.githubusercontent.com/94128405/184863826-59359886-df6b-429e-9493-3bad107b7552.png)

Ofcourse I leave it to you to make sure the position and  colours used look good and also (atleast partly) match the colours on the website

Both images can be found on the homepage of the website

Message 1: Can You Bust Out Within 60 Minutes?
Message 2: Award Winning Escape In Slough
Message 3: Use 10% Off Discount Code: SECONDLOOK10
Message 4: Go!

Regards

Rashed

**Comment by rashedethical** [comment]
@SufyanMussood any update on this?

**Comment by SufyanMussood** [comment]
Oh wow, I completely forgot about this Rash, apologies but I've been back to back on other businesses. 

Can I get this wrapped tomorrow.

**Comment by rashedethical** [comment]
Not to worry.

Tomorrow at the absolute latest is fine with me.

Please consider this a hard deadline, as I will get asked about this on Thursday.

**Comment by SufyanMussood** [comment]
hey rash, 

both 1x1 and 1.9.1 files have been added to Teams in the following location:

general - social assets - slough - retargeting ad

**Comment by rashedethical** [comment]
Hey @SufyanMussood, thanks for putting this together. Can you make the last slide with the discount code last a little longer please. We also need the same ads for the Essex site please. Thanks.

**Comment by SufyanMussood** [comment]
For the essex ad, I'm guessing the only thing I'm changing is the copy from Slough to Essex?

Would award winning escape room in essex make sense though? Also the imagery i have right now shown at the start is the escape rooms in slough not essex.

**Comment by SufyanMussood** [comment]
reuploaded the ads and increased the duration of the promo screen. 

Let me know what you want to do with the Essex ad?

**Comment by rashedethical** [comment]
Instead of award winning escape room in Essex, can you have 'Exciting new escape room in Essex'. Thankyou.

**Comment by SufyanMussood** [comment]
hey rash, thats now been added in teams in the essex folder.

**Comment by rashedethical** [comment]
Great. thanks.

**Comment by rashedethical** [comment]
Hi @SufyanMussood, 

I'm opening this again as some minor edits are needed. 

- Can you save the ad that you've created as a video format for use on YouTube please.
- Also can you create still images that that mentions the 'award winning escape room ins lough/exciting new escape room in Essex' message and the discount code message.  

Image details:

- 1.91:1, minimum 600 x 314
- 1:1, minimum 300 x 300
- PNG

Thanks.

**Comment by SufyanMussood** [comment]
Hey the mp4 files have been added to Team. When you have the youtube credentials, let me know please.

**Comment by rashedethical** [comment]
Will do.

**Comment by SufyanMussood** [comment]
![Homepage+Image+1+Idea+2309](https://user-images.githubusercontent.com/94172350/186650213-ac8de810-3d79-4795-be6d-753e0951fb84.jpg)
![Homepage+Image+1+Idea+2 00_00_08_24 Still002](https://user-images.githubusercontent.com/94172350/186650214-6482ed89-ea27-4a3e-8cae-99e4d0b37962.png)
![Homepage+Image+1+Idea+2 00_00_09_01 Still001](https://user-images.githubusercontent.com/94172350/186650216-c2a06d08-5d97-432e-9b5d-4c7ac713d64e.png)
![Homepage+Image+1+Idea+2 00_00_09_03 Still001](https://user-images.githubusercontent.com/94172350/186650218-d6c5a4b3-e066-420e-822a-5327eb5d2661.png)

**Comment by rashedethical** [comment]
Thanks.
